name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: nothingfortune/workflows/.github/workflows/ci.yml@6fdf3b6debe617006bd902d6d6384bb9252d1ffe # v1
