name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: nothingfortune/workflows/.github/workflows/ci.yml@93eb4896f38d60399fe61a7e4729bbe5ea0420db # v1
