name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: nothingfortune/workflows/.github/workflows/ci.yml@1f28f5a63001481511a35d5d278ec2198a2da245 # v1
